### ISSUE TITLE
Problem bei der Ausführung auf unterschiedlichen Rechnern (Clients bleiben hängen)

### ISSUE THREAD

**Issue by jfuerlinger** [GottaCode-Unity/Disskort#2]
Lt. Meldung von @GottaCode-Unity bleiben die Clients bei einer Ausführung der Server-/Client-Komponente auf unterschiedlichen Rechnern "hängen".

Folgende Tasks habe ich soeben durchgeführt:

1. Bereinigung der Projektstruktur (beide C#-Projekte in eine Solution).
2. Port des Server-Socket auf 6666 geändert.
3. Settings in Konfigurationsdatei ausgelagert.
4. Einige Bypässe zum Testen hinzugefügt. Können über die Konfiugrationsdateien aktiviert/deaktiviert werden.
5. SendMessage-Methode implementiert (Codeverdopplung reduziert).
6. Task.Delay zw. Senden und Empfangen von Messages hinzugefügt.

Mit dieser Code-Basis hat die Kommunikation zwischen verschiedenen Rechnern bei mir nun geklappt.

**Comment by GottaCode-Unity** [comment]
Danke sieht sehr schön aus. Aber ein paar sachen muss ich noch lernen. :) Wie ich die Konfigurationsdatei ändere weiß ich nicht. Danke

**Comment by GottaCode-Unity** [comment]
Ich habe mir einen Windows Server bei azure gemietet. Muss ich bzgl. Ports etwas beachten? Und braucht der Client anfangs Adminzugang bei der Firewall?

**Comment by GottaCode-Unity** [comment]
Sehr gut umgesetzt bis auf einen Bug ;)
